### ISSUE TITLE
Project renaming considerations

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/graph-analyzer#6]
I think we should simplify project names, e.g.

* [x] `test.model` -> `testmodels`
* [ ] modeladapters -> adapters
* [ ] modelmetrics -> metrics

**Comment by szarnyasg** [comment]
I performed the first rename, `tests.model.*` projects to `testmodels.*` and the `tests.model` project to `testbase`.

**Comment by szarnyasg** [comment]
We should leave the `modeladapters` and the `modelmetrics` projects as they are.

**Comment by zkovari** [comment]
I agree, as mentioned in the last discussion, currently a base, kind of general layer of metrics is distinguished from the model oriented ones to support the integration with further query or workload based metrics in the future.  Of course, to do so, the top layer still requires a lot of improvements, but I already have some plans for this.
